-- +goose Up
-- Rol ve yetki kataloğu: referans veridir, uygulama mantığı bu kodlara dayanır.
-- Kaynak: docs/mimari/03-kimlik-dogrulama-ve-yetkilendirme.md §4.2-4.4

INSERT INTO iam.roles (code, name_tr, name_en, scope_type, description) VALUES
    ('STUDENT', 'Öğrenci', 'Student', 'NONE', 'Ders seçer, içeriklere erişir, notlarını ve transkriptini görür.'),
    ('INSTRUCTOR', 'Öğretim Elemanı', 'Instructor', 'DEPARTMENT', 'Şube yetkileri section_instructors ilişkisinden gelir.'),
    ('ADVISOR', 'Danışman', 'Advisor', 'DEPARTMENT', 'Öğrenci yetkileri danışman ataması ilişkisinden gelir.'),
    ('DEPARTMENT_HEAD', 'Bölüm Başkanı', 'Head of Department', 'DEPARTMENT', 'Ders açma, kontenjan, ekle-bırak onayı, bölüm analitiği.'),
    ('FACULTY_REGISTRAR', 'Fakülte Öğrenci İşleri', 'Faculty Registrar', 'FACULTY', 'Öğrenci kayıtları, müfredat eşleştirme, not düzeltme onayı, belgeler.'),
    ('FACULTY_DEAN', 'Dekan / Dekan Yardımcısı', 'Dean', 'FACULTY', 'Fakülte analitiği ve üst onaylar.'),
    ('CENTRAL_REGISTRAR', 'Öğrenci İşleri Daire Başkanlığı', 'Central Registrar', 'UNIVERSITY', 'Takvim, dönemler, not ölçeği, yönetmelik parametreleri.'),
    ('FINANCE_OFFICER', 'Mali İşler', 'Finance Officer', 'UNIVERSITY', 'Katkı payı ve kayıt engelleri.'),
    ('RECTORATE_VIEWER', 'Rektörlük (salt okuma)', 'Rectorate Viewer', 'UNIVERSITY', 'Üniversite geneli analitik.'),
    ('SYSTEM_ADMIN', 'Sistem Yöneticisi', 'System Administrator', 'UNIVERSITY', 'Kullanıcı ve rol yönetimi. Akademik veriyi değiştiremez (görevler ayrılığı).'),
    ('AUDITOR', 'Denetçi', 'Auditor', 'UNIVERSITY', 'Denetim izi ve güvenlik olaylarını salt okuma.');

INSERT INTO iam.permissions (code, description, requires_mfa) VALUES
    ('session:manage_own',            'Kendi oturumlarını listeleme ve sonlandırma', false),
    ('profile:read_own',              'Kendi profilini görüntüleme', false),
    ('profile:update_own',            'Kendi profilini güncelleme', false),
    ('user:read',                     'Kullanıcı hesaplarını görüntüleme', false),
    ('user:manage',                   'Kullanıcı hesabı oluşturma, askıya alma, kapatma', true),
    ('role:assign',                   'Rol atama ve kaldırma', true),
    ('audit:read',                    'Denetim izini ve güvenlik olaylarını okuma', true),
    ('org:read',                      'Organizasyon yapısını görüntüleme', false),
    ('org:manage',                    'Fakülte, bölüm ve program tanımlama', false),
    ('classroom:manage',              'Bina ve derslik yönetimi', false),
    ('person:read',                   'Kapsamdaki kişilerin bilgilerini görüntüleme', false),
    ('person:manage',                 'Kişi kayıtlarını oluşturma ve düzenleme', false),
    ('advisor:assign',                'Danışman atama', false),
    ('calendar:read',                 'Akademik takvimi görüntüleme', false),
    ('calendar:manage',               'Akademik takvim ve dönem yönetimi', true),
    ('course:read',                   'Ders kataloğunu görüntüleme', false),
    ('course:manage',                 'Ders kataloğu yönetimi', false),
    ('curriculum:read',               'Müfredatı görüntüleme', false),
    ('curriculum:manage',             'Müfredat ve seçmeli grup yönetimi', false),
    ('gradescale:manage',             'Not ölçeği yönetimi', true),
    ('offering:manage',               'Ders açma', false),
    ('section:manage',                'Şube yönetimi', false),
    ('schedule:manage',               'Ders programı yönetimi', false),
    ('quota:manage',                  'Kontenjan yönetimi', false),
    ('assessment_plan:manage',        'Şubenin değerlendirme planını düzenleme', false),
    ('registration:manage_own',       'Kendi ders seçimini yapma', false),
    ('registration:approve',          'Danışmanlığındaki öğrencilerin ders seçimini onaylama', false),
    ('registration:approve_add_drop', 'Ekle-bırak taleplerini onaylama', false),
    ('registration:override',         'Takvim penceresi dışında kayıt işlemi (gerekçe zorunlu)', true),
    ('student_program:manage',        'Öğrenci program kaydı yönetimi', false),
    ('hold:manage',                   'Kayıt engeli koyma ve kaldırma', false),
    ('score:enter',                   'Değerlendirme bileşeni notu girme', true),
    ('grade:finalize',                'Harf notlarını kesinleştirme ve ilan etme', true),
    ('grade:read_own',                'Kendi notlarını görüntüleme', false),
    ('grade:read_section',            'Verdiği şubenin notlarını görüntüleme', false),
    ('grade:read_scoped',             'Kapsamdaki öğrencilerin notlarını görüntüleme', false),
    ('grade_change:request',          'Not düzeltme talebi oluşturma', false),
    ('grade_change:approve',          'Not düzeltme talebini onaylama', true),
    ('transcript:read_own',           'Kendi transkriptini görüntüleme', false),
    ('transcript:read_scoped',        'Kapsamdaki öğrencilerin transkriptini görüntüleme', false),
    ('attendance:take',               'Yoklama alma', false),
    ('attendance:read_own',           'Kendi devamsızlığını görüntüleme', false),
    ('attendance:read_section',       'Şubenin yoklamasını görüntüleme', false),
    ('lms:read_enrolled',             'Kayıtlı olduğu ders alanlarına erişme', false),
    ('lms:content_manage',            'Ders alanı içeriği yönetimi', false),
    ('lms:submit_own',                'Ödev teslim etme ve sınava girme', false),
    ('lms:grade_submissions',         'Teslimleri puanlama', false),
    ('quiz:manage',                   'Sınav ve soru bankası yönetimi', false),
    ('announcement:read',             'Duyuruları okuma', false),
    ('announcement:publish',          'Kapsamına duyuru yayınlama', false),
    ('message:send',                  'Mesaj gönderme', false),
    ('notification:read_own',         'Kendi bildirimlerini görüntüleme', false),
    ('survey:respond_own',            'Kendisine atanan anketleri yanıtlama', false),
    ('survey:manage',                 'Anket tanımlama', false),
    ('survey:results_read',           'Anket sonuçlarını (toplu) görüntüleme', false),
    ('document:request_own',          'Kendisi için belge talep etme', false),
    ('document:process',              'Belge taleplerini işleme', false),
    ('application:submit_own',        'Başvuru ve dilekçe oluşturma', false),
    ('application:review',            'Başvuruları değerlendirme', false),
    ('analytics:read_scoped',         'Kapsamındaki analitik panelleri görüntüleme', false),
    ('ticket:create_own',             'Yardım masası talebi oluşturma', false),
    ('ticket:handle',                 'Yardım masası taleplerini yanıtlama', false);

-- Her rolün ortak temel yetkileri (giriş yapmış her kullanıcının ihtiyacı olanlar).
INSERT INTO iam.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM iam.roles r
CROSS JOIN iam.permissions p
WHERE p.code IN (
    'session:manage_own',
    'profile:read_own',
    'profile:update_own',
    'org:read',
    'calendar:read',
    'course:read',
    'curriculum:read',
    'announcement:read',
    'message:send',
    'notification:read_own',
    'ticket:create_own'
);

-- Role özgü yetkiler.
INSERT INTO iam.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM (VALUES
    ('STUDENT', 'registration:manage_own'),
    ('STUDENT', 'grade:read_own'),
    ('STUDENT', 'transcript:read_own'),
    ('STUDENT', 'attendance:read_own'),
    ('STUDENT', 'lms:read_enrolled'),
    ('STUDENT', 'lms:submit_own'),
    ('STUDENT', 'survey:respond_own'),
    ('STUDENT', 'document:request_own'),
    ('STUDENT', 'application:submit_own'),
    ('INSTRUCTOR', 'assessment_plan:manage'),
    ('INSTRUCTOR', 'score:enter'),
    ('INSTRUCTOR', 'grade:finalize'),
    ('INSTRUCTOR', 'grade:read_section'),
    ('INSTRUCTOR', 'grade_change:request'),
    ('INSTRUCTOR', 'attendance:take'),
    ('INSTRUCTOR', 'attendance:read_section'),
    ('INSTRUCTOR', 'lms:read_enrolled'),
    ('INSTRUCTOR', 'lms:content_manage'),
    ('INSTRUCTOR', 'lms:grade_submissions'),
    ('INSTRUCTOR', 'quiz:manage'),
    ('INSTRUCTOR', 'announcement:publish'),
    ('INSTRUCTOR', 'survey:results_read'),
    ('INSTRUCTOR', 'analytics:read_scoped'),
    ('ADVISOR', 'registration:approve'),
    ('ADVISOR', 'transcript:read_scoped'),
    ('ADVISOR', 'grade:read_scoped'),
    ('ADVISOR', 'person:read'),
    ('ADVISOR', 'analytics:read_scoped'),
    ('DEPARTMENT_HEAD', 'registration:approve_add_drop'),
    ('DEPARTMENT_HEAD', 'offering:manage'),
    ('DEPARTMENT_HEAD', 'section:manage'),
    ('DEPARTMENT_HEAD', 'schedule:manage'),
    ('DEPARTMENT_HEAD', 'quota:manage'),
    ('DEPARTMENT_HEAD', 'grade_change:approve'),
    ('DEPARTMENT_HEAD', 'transcript:read_scoped'),
    ('DEPARTMENT_HEAD', 'grade:read_scoped'),
    ('DEPARTMENT_HEAD', 'person:read'),
    ('DEPARTMENT_HEAD', 'advisor:assign'),
    ('DEPARTMENT_HEAD', 'announcement:publish'),
    ('DEPARTMENT_HEAD', 'survey:results_read'),
    ('DEPARTMENT_HEAD', 'analytics:read_scoped'),
    ('FACULTY_REGISTRAR', 'registration:override'),
    ('FACULTY_REGISTRAR', 'student_program:manage'),
    ('FACULTY_REGISTRAR', 'hold:manage'),
    ('FACULTY_REGISTRAR', 'grade_change:approve'),
    ('FACULTY_REGISTRAR', 'transcript:read_scoped'),
    ('FACULTY_REGISTRAR', 'grade:read_scoped'),
    ('FACULTY_REGISTRAR', 'person:read'),
    ('FACULTY_REGISTRAR', 'person:manage'),
    ('FACULTY_REGISTRAR', 'advisor:assign'),
    ('FACULTY_REGISTRAR', 'offering:manage'),
    ('FACULTY_REGISTRAR', 'section:manage'),
    ('FACULTY_REGISTRAR', 'schedule:manage'),
    ('FACULTY_REGISTRAR', 'quota:manage'),
    ('FACULTY_REGISTRAR', 'curriculum:manage'),
    ('FACULTY_REGISTRAR', 'document:process'),
    ('FACULTY_REGISTRAR', 'application:review'),
    ('FACULTY_REGISTRAR', 'announcement:publish'),
    ('FACULTY_REGISTRAR', 'analytics:read_scoped'),
    ('FACULTY_DEAN', 'transcript:read_scoped'),
    ('FACULTY_DEAN', 'grade:read_scoped'),
    ('FACULTY_DEAN', 'person:read'),
    ('FACULTY_DEAN', 'application:review'),
    ('FACULTY_DEAN', 'announcement:publish'),
    ('FACULTY_DEAN', 'analytics:read_scoped'),
    ('CENTRAL_REGISTRAR', 'calendar:manage'),
    ('CENTRAL_REGISTRAR', 'gradescale:manage'),
    ('CENTRAL_REGISTRAR', 'course:manage'),
    ('CENTRAL_REGISTRAR', 'curriculum:manage'),
    ('CENTRAL_REGISTRAR', 'org:manage'),
    ('CENTRAL_REGISTRAR', 'classroom:manage'),
    ('CENTRAL_REGISTRAR', 'registration:override'),
    ('CENTRAL_REGISTRAR', 'student_program:manage'),
    ('CENTRAL_REGISTRAR', 'transcript:read_scoped'),
    ('CENTRAL_REGISTRAR', 'grade:read_scoped'),
    ('CENTRAL_REGISTRAR', 'person:read'),
    ('CENTRAL_REGISTRAR', 'person:manage'),
    ('CENTRAL_REGISTRAR', 'document:process'),
    ('CENTRAL_REGISTRAR', 'announcement:publish'),
    ('CENTRAL_REGISTRAR', 'analytics:read_scoped'),
    ('FINANCE_OFFICER', 'hold:manage'),
    ('FINANCE_OFFICER', 'person:read'),
    ('RECTORATE_VIEWER', 'analytics:read_scoped'),
    ('SYSTEM_ADMIN', 'user:read'),
    ('SYSTEM_ADMIN', 'user:manage'),
    ('SYSTEM_ADMIN', 'role:assign'),
    ('SYSTEM_ADMIN', 'ticket:handle'),
    ('SYSTEM_ADMIN', 'survey:manage'),
    ('AUDITOR', 'audit:read'),
    ('AUDITOR', 'user:read')
) AS v(role_code, permission_code)
JOIN iam.roles r ON r.code = v.role_code
JOIN iam.permissions p ON p.code = v.permission_code;

-- +goose Down
DELETE FROM iam.role_permissions;
DELETE FROM iam.permissions;
DELETE FROM iam.roles;
