-- Geliştirme seed'i: Bilgisayar Mühendisliği (İngilizce) programının gerçek ders planları.
--
-- Kaynak: bölümün yayımladığı ders planı formları (2022, 2023 ve 2026 sürümleri). Bu dosya
-- formlardan ayrıştırılan veriden üretilmiştir; elle düzenlemeyin, üreticiyi yeniden
-- çalıştırın (infra/seed/source/bm-curriculum/README.md). 2024 formu okunamadığı için
-- 2023-2025 girişlileri 2023 sürümünü izler.
--
-- Dersler, saatleri, kredileri ve AKTS'leri formlardaki gibidir. Formlarda listelenmeyen
-- üniversite alan dışı seçmeli havuzu için birkaç sentetik ders (UNVG...) eklenmiştir.
-- Eşdeğerlikler 2026 formunun intibak sütunundan ve aynı adlı derslerin kod
-- değişikliklerinden çıkarılmıştır. Tekrar çalıştırılabilir.

-- Dersler
INSERT INTO curriculum.courses (code, owner_department_id, name_tr, name_en, theory_hours, practice_hours,
                                national_credit, ects, language, course_kind, grading_mode, description_tr, description_en)
SELECT v.code, d.id, v.name_tr, v.name_en, v.theory, v.practice, v.credit, v.ects, v.lang, v.kind, v.mode, v.dtr, v.den
FROM (VALUES
    ('ART107', NULL, 'Resim', 'Painting', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('ART109', NULL, 'Müzik', 'Music', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('ART111', NULL, 'Heykel', 'Sculpture', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('ART123', NULL, 'Halk Oyunları', 'Folk Dance', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('ART131', NULL, 'Drama', 'Drama', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('ART163', NULL, 'Müze Eğitimi', 'Museum Training', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('ART219', NULL, 'Modern Dans', 'Modern Dance', 0, 2, 0.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('BME3314', 'BME', 'Mikroişlemciler', 'Microprocessors', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('BME3336', 'BME', 'Polimer Mühendisliğine Giriş', 'Introduction to Polymer Engineering', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('BME3346', 'BME', 'Nanotıp', 'Nanomedicine', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('CEN3338', NULL, 'Dinamik Benzetime Giriş', 'Introduction to Dynamic Simulation', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('CEN338', NULL, 'Dinamik Benzetime Giriş', 'Introduction to Dynamic Simulation', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM1001', 'BIL', 'Bilgisayar Programlama I', 'Computer Programming I', 4, 2, 5.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM1002', 'BIL', 'Bilgisayar Programlama II', 'Computer Programming II', 4, 2, 5.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM1007', 'BIL', 'Bilgisayar Programlama I', 'Computer Programming I', 4, 2, 5.0, 7.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM1013', 'BIL', 'Bilgisayar Bilimlerine Giriş', 'Introduction to Computer Science', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM1015', 'BIL', 'Bilgisayar Bilimlerine Giriş', 'Introduction to Computer Science', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2031', 'BIL', 'Ayrık Yapılar', 'Discrete Structures', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2039', 'BIL', 'Ayrık Yapılar', 'Discrete Structures', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2041', 'BIL', 'Programlama Dili Kavramları', 'Programming Language Concepts', 3, 2, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2043', 'BIL', 'Programlama Dili Kavramları', 'Programming Language Concepts', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2044', 'BIL', 'Nesne Yönelimli Programlama', 'Object Oriented Programming', 3, 2, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2058', 'BIL', 'Veritabanı Yönetimi', 'Database Management', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2067', 'BIL', 'Veri Yapıları', 'Data Structures', 3, 2, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2075', 'BIL', 'Sayısal Mantık Tasarımı', 'Digital Logic Design', 3, 2, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2077', 'BIL', 'Sayısal Mantık Tasarımı', 'Digital Logic Design', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2501', 'BIL', 'Bilimsel Programlama', 'Scientific Programming', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2502', 'BIL', 'Veri Bilimine Giriş', 'Introduction to Data Science', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2534', 'BIL', 'Elektronik', 'Electronics', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2536', 'BIL', 'Bulanık Mantık', 'Fuzzy Logic', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2537', 'BIL', 'Ağ Tabanlı Programlamaya Giriş', 'Introduction to Web Based Programming', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM2553', 'BIL', 'Dosya Organizasyonu', 'File Organization', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3023', 'BIL', 'Mikroişlemciler ve Gömülü Sistemler', 'Microprocessors and Embedded Systems', 3, 2, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3025', 'BIL', 'Mikroişlemciler ve Gömülü Sistemler', 'Microprocessors and Embedded Systems', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3032', 'BIL', 'Bilgisayar Ağları', 'Computer Networks', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3033', 'BIL', 'İşletim Sistemleri', 'Operating Systems', 3, 2, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3035', 'BIL', 'İşletim Sistemleri', 'Operating Systems', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3037', 'BIL', 'Bilgisayar Grafıkleri', 'Computer Graphics', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3064', 'BIL', 'Otomata Teorisi', 'Automata Theory', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3066', 'BIL', 'Otomata Teorisi', 'Automata Theory', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3067', 'BIL', 'Algoritmalar', 'Algorithms', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3068', 'BIL', 'Yazılım Mühendisliği', 'Software Engineering', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3070', 'BIL', 'Yazılım Mühendisliği', 'Software Engineering', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3071', 'BIL', 'İş Sağlığı ve Güvenliği I', 'Occupational Health and Safety I', 1, 0, 1.0, 1.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3072', 'BIL', 'İş Sağlığı ve Güvenliği II', 'Occupational Health and Safety II', 1, 0, 1.0, 1.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3073', 'BIL', 'İş Sağlığı ve Güvenliği I', 'Occupational Health and Safety I', 2, 0, 2.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3074', 'BIL', 'İş Sağlığı ve Güvenliği II', 'Occupational Health and Safety II', 2, 0, 2.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3076', 'BIL', 'Bilgisayar Mimarisi', 'Computer Architecture', 3, 2, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3525', 'BIL', 'Mikroişlemciler ve Gömülü Sistemler', 'Microprocessors and Embedded Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3533', 'BIL', 'Sayısal Analiz Teknikleri', 'Numerical Analysis Methods', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3536', 'BIL', 'Sinyaller ve Sistemler', 'Signals and Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3537', 'BIL', 'Bilgisayar Grafikleri', 'Computer Graphics', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3542', 'BIL', 'İleri Algoritmalar', 'Advanced Algorithms', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3548', 'BIL', 'Örüntü Tanıma', 'Pattern Recognition', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3549', 'BIL', 'Paralel Veri İşleme', 'Parallel Data Processing', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3551', 'BIL', 'Yapay Zeka', 'Artificial Intelligence', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3557', 'BIL', 'Veri İletişimi', 'Data Communication', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3576', 'BIL', 'Uzman Sistemler', 'Expert Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM3596', 'BIL', 'Bilgisayar Simülasyonu ve Modelleme', 'Computer Simulation and Modeling', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4061', 'BIL', 'Araştırma Teknikleri I', 'Research Techniques I', 2, 2, 3.0, 6.0, 'EN', 'PROJECT', 'LETTER', NULL, NULL),
    ('COM4062', 'BIL', 'Araştırma Teknikleri II', 'Research Techniques II', 2, 2, 3.0, 6.0, 'EN', 'PROJECT', 'LETTER', NULL, NULL),
    ('COM4063', 'BIL', 'Mezuniyet Projesi I', 'Graduation Project I', 2, 2, 3.0, 7.0, 'EN', 'PROJECT', 'LETTER', NULL, NULL),
    ('COM4064', 'BIL', 'Mezuniyet Projesi II', 'Graduation Project II', 2, 2, 3.0, 7.0, 'EN', 'PROJECT', 'LETTER', NULL, NULL),
    ('COM4080', 'BIL', 'Sayısal Görüntü İşleme', 'Digital Image Processing', 3, 2, 4.0, 7.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4097', 'BIL', 'Staj', 'Summer Practice', 0, 0, 0.0, 7.0, 'EN', 'INTERNSHIP', 'PASS_FAIL', 'Staj, 4. yarıyıl sonundan itibaren yapılabilir.', 'Summer practice can be done after the end of the 4th semester.'),
    ('COM4099', 'BIL', 'Staj', 'Summer Practice', 0, 0, 0.0, 6.0, 'EN', 'INTERNSHIP', 'PASS_FAIL', 'Staj, 4. yarıyıl sonundan itibaren yapılabilir.', 'Summer practice can be done after the end of the 4th semester.'),
    ('COM4501', 'BIL', 'Mobil Cihazlar için Android İşletim Sistemi', 'Android Operating System For Mobile Devices', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4502', 'BIL', 'Android İşletim Sistemi ile Uygulamalar Geliştirme', 'Applications Development with Android Operating System', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4503', 'BIL', 'İleri Mikroişlemciler', 'Advanced Microprocessors', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4504', 'BIL', 'Sayısal Görüntü İşleme', 'Digital Image Processing', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4505', 'BIL', 'RFID ve Bilgisayar Uygulamaları', 'RFID and Computer Applications', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4506', 'BIL', 'Donanım Tasarım Dilleri', 'Hardware Design Languages', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4507', 'BIL', 'Robotik', 'Robotics', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4508', 'BIL', 'İleri Elektronik', 'Advanced Electronics', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4509', 'BIL', 'Uzaktan Algılama', 'Remote Sensing', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4510', 'BIL', 'Bilgi Teknolojileri ve Güvenlik Yönetimi', 'Information Technology and Security Governance', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4511', 'BIL', 'Bilgi Teknolojileri Yönetimi', 'Information Technologies Management', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4512', 'BIL', 'Kablosuz İletişim ve Bilgisayar Ağları', 'Wireless Communication and Computer Networks', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4513', 'BIL', 'Özel Konular I', 'Special Topics I', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4514', 'BIL', 'Özel Konular II', 'Special Topics II', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4515', 'BIL', 'İleri İşletim Sistemleri', 'Advanced Operating Systems', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4516', 'BIL', 'Paralel Programlama', 'Parallel Programming', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4517', 'BIL', 'Bilgi Sistemleri', 'Information Systems', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4518', 'BIL', 'İleri Bilgisayar Ağları', 'Advanced Computer Networks', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4519', 'BIL', 'Veri Madenciliği', 'Data Mining', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4520', 'BIL', 'CISCO', 'CISCO', 3, 0, 3.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4541', 'BIL', 'Yapay Zeka Destekli Yazılım Mühendisliği', 'AI-Assisted Software Engineering', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4551', 'BIL', 'Mobil Cihazlar İçin Android İşletim Sistemi', 'Android Operating System for Mobile Devices', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4552', 'BIL', 'Android İşletim Sistemi ile Uygulamalar Geliştirme', 'Applications Development with Android Operating System', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4553', 'BIL', 'İleri Mikroişlemciler', 'Advanced Microprocessors', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4555', 'BIL', 'RFID ve Bilgisayar Uygulamaları', 'RFID and Computer Applications', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4556', 'BIL', 'Donanım Tasarım Dilleri', 'Hardware Design Languages', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4557', 'BIL', 'Robotik', 'Robotics', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4558', 'BIL', 'İleri Elektronik', 'Advanced Electronics', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4559', 'BIL', 'Uzaktan Algılama', 'Remote Sensing', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4560', 'BIL', 'Bilgi Teknolojileri ve Güvenlik Yönetimi', 'Information Technology and Security Governance', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4561', 'BIL', 'Bilgi Teknolojileri Yönetimi', 'Information Technologies Management', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4562', 'BIL', 'Kablosuz İletişim ve Bilgisayar Ağları', 'Wireless Communication and Computer Networks', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4565', 'BIL', 'İleri İşletim Sistemleri', 'Advanced Operating Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4566', 'BIL', 'Paralel Programlama', 'Parallel Programming', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4567', 'BIL', 'Bilgi Sistemleri', 'Information Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4568', 'BIL', 'İleri Bilgisayar Ağları', 'Advanced Computer Networks', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4569', 'BIL', 'Veri Madenciliği', 'Data Mining', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4572', 'BIL', 'Ağ Tabanlı Paralel Dağıtım Sistemleri', 'Web Based Parallel Distributed Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4573', 'BIL', 'Yapay Sinir Ağları', 'Artificial Neural Networks', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4574', 'BIL', 'Karmaşık Ağlara Giriş', 'Introduction to Complex Networks', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4575', 'BIL', 'Gömülü Sistem Programlama', 'Embedded System Programming', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4576', 'BIL', 'Gömülü Sistem Tasarımı', 'Embedded System Design', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4577', 'BIL', 'Sistem Yönetimi', 'System Management', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4578', 'BIL', 'Mikroişlemci Arayüzleri', 'Microprocessor Interfaces', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4579', 'BIL', 'Gerçek Zamanlı Sistemler', 'Real-Time Systems', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4580', 'BIL', 'Bilgi Güvenliği', 'Information Security', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4581', 'BIL', 'Ağ Tabanlı Teknolojiler ve Uygulamaları', 'Web Based Technologies and Applications', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4582', 'BIL', 'Blokzinciri Teknolojisi ve Açık Defterler', 'Blockchain Technology and Public Ledgers', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4583', 'BIL', 'Nesne Yönelimli Yazılım Modelleme', 'Object Oriented Software Modeling', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4584', 'BIL', 'Bilgi Mühendisliği ve Yönetimi', 'Knowledge Engineering and Management', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4585', 'BIL', 'Uygulamalı Kriptografi', 'Applied Cryptography', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4587', 'BIL', 'IOS ile Mobil Uygulama Geliştirme I', 'iOS Mobile Application Development I', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4588', 'BIL', 'IOS ile Mobil Uygulama Geliştirme II', 'iOS Mobile Application Development II', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4590', 'BIL', 'Derin Öğrenme', 'Deep Learning', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('COM4594', 'BIL', 'Doğal Dil İşleme', 'Natural Language Processing', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('EEE317', 'EEM', 'Modelleme ve Benzetim', 'Modeling and Simulation', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('EEE328', 'EEM', 'Sayısal İşaret İşleme', 'Digital Signal Processing', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('ENE355', NULL, 'Ölçme ve Enstrümantasyon', 'Measurement and Instrumentation', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('ENE356', NULL, 'Nanobilim ve Nanoteknoloji', 'Nanoscience and Nanotechnology', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('ENG101', NULL, 'İngilizce Okuma ve Yazma Becerilerinin Geliştirilmesi I', 'Development of Reading and Writing Skills in English I', 4, 0, 4.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('ENG102', NULL, 'İngilizce Okuma ve Yazma Becerilerinin Geliştirilmesi II', 'Development of Reading and Writing Skills in English II', 4, 0, 4.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('ENG201', NULL, 'İngilizce İleri Okuma ve İletişim Teknikleri I', 'Advanced Reading And Communication Techniques In English I', 4, 0, 4.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('ENG202', NULL, 'İngilizce İleri Okuma ve İletişim Teknikleri II', 'Advanced Reading And Communication Techniques In English II', 4, 0, 4.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('HIS101', NULL, 'Atatürk İlkeleri ve İnkilap Tarihi I', 'Ataturk''s Principles and History of Revolution I', 2, 0, 2.0, 1.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('HIS102', NULL, 'Atatürk İlkeleri ve İnkilap Tarihi II', 'Ataturk''s Principles and History of Revolution II', 2, 0, 2.0, 1.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('HIS103', NULL, 'Atatürk İlkeleri ve İnkilap Tarihi I', 'Ataturk''s Principles and History of Revolution I', 2, 0, 2.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('HIS104', NULL, 'Atatürk İlkeleri ve İnkilap Tarihi II', 'Ataturk''s Principles and History of Revolution II', 2, 0, 2.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('MTH0120', 'MAT', 'Lineer Cebir', 'Linear Algebra', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('MTH0141', 'MAT', 'Matematik I', 'Calculus I', 4, 0, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('MTH0142', 'MAT', 'Matematik II', 'Calculus II', 4, 0, 4.0, 6.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('MTH0143', 'MAT', 'Matematik I', 'Calculus I', 4, 0, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('MTH0144', 'MAT', 'Matematik II', 'Calculus II', 4, 0, 4.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('MTH0210', 'MAT', 'Diferansiyel Denklemler', 'Differential Equations', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('OUL101', NULL, 'Üniversite Yaşamına Uyum', 'Orientation Program to the University Life', 0, 0, 0.0, 0.0, 'TR', 'NON_CREDIT', 'PASS_FAIL', NULL, NULL),
    ('OUL102', NULL, 'Üniversite Yaşamına Uyum ve Yaşam Becerileri', 'Orientation to University Life and Life Skills', 1, 0, 1.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PEN218', NULL, 'Ölçme Yöntemlerine Giriş', 'Introduction to Measurement Methods', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE001', NULL, 'Eğitime Giriş', 'Introduction to Education', 3, 0, 3.0, 4.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE002', NULL, 'Öğretim İlke ve Yöntemleri', 'Instructional Principles and Methods', 3, 0, 3.0, 4.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE003', NULL, 'Sınıf Yönetimi', 'Classroom Management', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE004', NULL, 'Özel Öğretim Yöntemleri', 'Special Teaching Methods', 3, 0, 3.0, 4.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE005', NULL, 'Rehberlik ve Özel Eğitim', 'Guidance and Special Education', 3, 0, 3.0, 4.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE006', NULL, 'Eğitimde Ölçme ve Değerlendirme', 'Measurement and Evaluation in Education', 3, 0, 3.0, 4.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE007', NULL, 'Eğitim Psikolojisi', 'Psychology of Education', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE008', NULL, 'Öğretim Teknolojileri', 'Instructional Technologies', 3, 0, 3.0, 4.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PFE009', NULL, 'Öğretmenlik Uygulaması', 'Teaching Practice', 1, 8, 5.0, 10.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('PHY0101', 'FIZ', 'Fizik I', 'Physics I', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PHY0102', 'FIZ', 'Fizik II', 'Physics II', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PHY0105', 'FIZ', 'Fizik I', 'Physics I', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PHY0106', 'FIZ', 'Fizik II', 'Physics II', 3, 0, 3.0, 4.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PHY0151', 'FIZ', 'Fizik Laboratuvarı I', 'Physics Laboratory I', 0, 2, 1.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PHY0152', 'FIZ', 'Fizik Laboratuvarı II', 'Physics Laboratory II', 0, 2, 1.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('PPL302', NULL, 'Mesleki Yaşama Uyum', 'Progress to Professional Life', 1, 0, 1.0, 2.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('SCS301', NULL, 'Bilimsel, Sosyal ve Kültürel Etkinlikler', 'Scientific, Cultural and Social Activities', 0, 0, 0.0, 3.0, 'EN', 'ACTIVITY', 'PASS_FAIL', NULL, NULL),
    ('STA250', 'IST', 'Olasılık ve İstatistik', 'Probability and Statistics', 3, 0, 3.0, 5.0, 'EN', 'REGULAR', 'LETTER', NULL, NULL),
    ('TUR101', NULL, 'Türk Dili I', 'Turkish Language I', 2, 0, 2.0, 1.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('TUR102', NULL, 'Türk Dili II', 'Turkish Language II', 2, 0, 2.0, 1.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('TUR171', NULL, 'Türk Dili I', 'Turkish Language I', 2, 0, 2.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('TUR174', NULL, 'Türk Dili II', 'Turkish Language II', 2, 0, 2.0, 2.0, 'TR', 'REGULAR', 'LETTER', NULL, NULL),
    ('UNVG101', NULL, 'Girişimcilik ve İnovasyon', 'Entrepreneurship and Innovation', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', 'Sentetik örnek ders: üniversite alan dışı seçmeli havuzu resmî ders planında listelenmediği için seed verisinde örneklenmiştir.', 'Synthetic sample course: the university out-of-field elective pool is not listed in the official plan, so it is sampled in seed data.'),
    ('UNVG103', NULL, 'Bilim Tarihi ve Felsefesi', 'History and Philosophy of Science', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', 'Sentetik örnek ders: üniversite alan dışı seçmeli havuzu resmî ders planında listelenmediği için seed verisinde örneklenmiştir.', 'Synthetic sample course: the university out-of-field elective pool is not listed in the official plan, so it is sampled in seed data.'),
    ('UNVG105', NULL, 'Sanat ve Toplum', 'Art and Society', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', 'Sentetik örnek ders: üniversite alan dışı seçmeli havuzu resmî ders planında listelenmediği için seed verisinde örneklenmiştir.', 'Synthetic sample course: the university out-of-field elective pool is not listed in the official plan, so it is sampled in seed data.'),
    ('UNVG107', NULL, 'Sürdürülebilir Kalkınma', 'Sustainable Development', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', 'Sentetik örnek ders: üniversite alan dışı seçmeli havuzu resmî ders planında listelenmediği için seed verisinde örneklenmiştir.', 'Synthetic sample course: the university out-of-field elective pool is not listed in the official plan, so it is sampled in seed data.'),
    ('UNVG109', NULL, 'Hukukun Temel Kavramları', 'Fundamentals of Law', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', 'Sentetik örnek ders: üniversite alan dışı seçmeli havuzu resmî ders planında listelenmediği için seed verisinde örneklenmiştir.', 'Synthetic sample course: the university out-of-field elective pool is not listed in the official plan, so it is sampled in seed data.'),
    ('UNVG111', NULL, 'Etkili İletişim', 'Effective Communication', 2, 0, 2.0, 3.0, 'TR', 'REGULAR', 'LETTER', 'Sentetik örnek ders: üniversite alan dışı seçmeli havuzu resmî ders planında listelenmediği için seed verisinde örneklenmiştir.', 'Synthetic sample course: the university out-of-field elective pool is not listed in the official plan, so it is sampled in seed data.')
) AS v(code, dept, name_tr, name_en, theory, practice, credit, ects, lang, kind, mode, dtr, den)
LEFT JOIN org.departments d ON d.code = v.dept
ON CONFLICT (code) DO NOTHING;

-- Seçmeli ders grupları (havuzlar)
INSERT INTO curriculum.elective_groups (code, name_tr, name_en, owner_department_id, group_kind)
SELECT v.code, v.name_tr, v.name_en, d.id, v.kind
FROM (VALUES
    ('COMTE02', '2. Sınıf Teknik Seçmeli Dersler', '2nd Year Technical Electives', 'BIL', 'TECHNICAL'),
    ('COMTE03', '3. Sınıf Teknik Seçmeli Dersler', '3rd Year Technical Electives', 'BIL', 'TECHNICAL'),
    ('COMTE04', '4. Sınıf Teknik Seçmeli Dersler', '4th Year Technical Electives', 'BIL', 'TECHNICAL'),
    ('GENELSOSSEC', 'Genel Sosyal Seçmeli Dersler', 'General Social Electives', NULL, 'SOCIAL'),
    ('PFESECG3YY', 'Pedagojik Formasyon Eğitimi Grubu (3. yarıyıl)', 'Pedagogical Formation Training Group (Semester 3)', NULL, 'PEDAGOGICAL'),
    ('PFESECG4YY', 'Pedagojik Formasyon Eğitimi Grubu (4. yarıyıl)', 'Pedagogical Formation Training Group (Semester 4)', NULL, 'PEDAGOGICAL'),
    ('PFESECG5YY', 'Pedagojik Formasyon Eğitimi Grubu (5. yarıyıl)', 'Pedagogical Formation Training Group (Semester 5)', NULL, 'PEDAGOGICAL'),
    ('PFESECG6YY', 'Pedagojik Formasyon Eğitimi Grubu (6. yarıyıl)', 'Pedagogical Formation Training Group (Semester 6)', NULL, 'PEDAGOGICAL'),
    ('PFESECG7YY', 'Pedagojik Formasyon Eğitimi Grubu (7. yarıyıl)', 'Pedagogical Formation Training Group (Semester 7)', NULL, 'PEDAGOGICAL'),
    ('UNVGOFECG', 'Üniversite Alan Dışı Genel Seçmeli Ders Grubu', 'University General Out-of-Field Electives', NULL, 'UNIVERSITY_GENERAL'),
    ('UNVSEC', 'Alan Dışı (Üniversite) Seçmeli Dersler', 'University Out-of-Field Electives', NULL, 'UNIVERSITY_GENERAL')
) AS v(code, name_tr, name_en, dept, kind)
LEFT JOIN org.departments d ON d.code = v.dept
ON CONFLICT (code) DO NOTHING;

INSERT INTO curriculum.elective_group_courses (elective_group_id, course_id)
SELECT g.id, c.id
FROM (VALUES
    ('COMTE02', 'COM2501'),
    ('COMTE02', 'COM2502'),
    ('COMTE02', 'COM2534'),
    ('COMTE02', 'COM2536'),
    ('COMTE02', 'COM2537'),
    ('COMTE02', 'COM2553'),
    ('COMTE02', 'PEN218'),
    ('COMTE03', 'BME3314'),
    ('COMTE03', 'BME3336'),
    ('COMTE03', 'BME3346'),
    ('COMTE03', 'CEN3338'),
    ('COMTE03', 'CEN338'),
    ('COMTE03', 'COM3525'),
    ('COMTE03', 'COM3533'),
    ('COMTE03', 'COM3536'),
    ('COMTE03', 'COM3537'),
    ('COMTE03', 'COM3542'),
    ('COMTE03', 'COM3548'),
    ('COMTE03', 'COM3549'),
    ('COMTE03', 'COM3551'),
    ('COMTE03', 'COM3557'),
    ('COMTE03', 'COM3576'),
    ('COMTE03', 'COM3596'),
    ('COMTE03', 'EEE317'),
    ('COMTE03', 'EEE328'),
    ('COMTE03', 'ENE355'),
    ('COMTE03', 'ENE356'),
    ('COMTE04', 'COM4501'),
    ('COMTE04', 'COM4502'),
    ('COMTE04', 'COM4503'),
    ('COMTE04', 'COM4504'),
    ('COMTE04', 'COM4505'),
    ('COMTE04', 'COM4506'),
    ('COMTE04', 'COM4507'),
    ('COMTE04', 'COM4508'),
    ('COMTE04', 'COM4509'),
    ('COMTE04', 'COM4510'),
    ('COMTE04', 'COM4511'),
    ('COMTE04', 'COM4512'),
    ('COMTE04', 'COM4513'),
    ('COMTE04', 'COM4514'),
    ('COMTE04', 'COM4515'),
    ('COMTE04', 'COM4516'),
    ('COMTE04', 'COM4517'),
    ('COMTE04', 'COM4518'),
    ('COMTE04', 'COM4519'),
    ('COMTE04', 'COM4520'),
    ('COMTE04', 'COM4541'),
    ('COMTE04', 'COM4551'),
    ('COMTE04', 'COM4552'),
    ('COMTE04', 'COM4553'),
    ('COMTE04', 'COM4555'),
    ('COMTE04', 'COM4556'),
    ('COMTE04', 'COM4557'),
    ('COMTE04', 'COM4558'),
    ('COMTE04', 'COM4559'),
    ('COMTE04', 'COM4560'),
    ('COMTE04', 'COM4561'),
    ('COMTE04', 'COM4562'),
    ('COMTE04', 'COM4565'),
    ('COMTE04', 'COM4566'),
    ('COMTE04', 'COM4567'),
    ('COMTE04', 'COM4568'),
    ('COMTE04', 'COM4569'),
    ('COMTE04', 'COM4572'),
    ('COMTE04', 'COM4573'),
    ('COMTE04', 'COM4574'),
    ('COMTE04', 'COM4575'),
    ('COMTE04', 'COM4576'),
    ('COMTE04', 'COM4577'),
    ('COMTE04', 'COM4578'),
    ('COMTE04', 'COM4579'),
    ('COMTE04', 'COM4580'),
    ('COMTE04', 'COM4581'),
    ('COMTE04', 'COM4582'),
    ('COMTE04', 'COM4583'),
    ('COMTE04', 'COM4584'),
    ('COMTE04', 'COM4585'),
    ('COMTE04', 'COM4587'),
    ('COMTE04', 'COM4588'),
    ('COMTE04', 'COM4590'),
    ('COMTE04', 'COM4594'),
    ('GENELSOSSEC', 'ART107'),
    ('GENELSOSSEC', 'ART109'),
    ('GENELSOSSEC', 'ART111'),
    ('GENELSOSSEC', 'ART123'),
    ('GENELSOSSEC', 'ART131'),
    ('GENELSOSSEC', 'ART163'),
    ('GENELSOSSEC', 'ART219'),
    ('PFESECG3YY', 'PFE001'),
    ('PFESECG3YY', 'PFE002'),
    ('PFESECG4YY', 'PFE003'),
    ('PFESECG4YY', 'PFE004'),
    ('PFESECG5YY', 'PFE005'),
    ('PFESECG5YY', 'PFE006'),
    ('PFESECG6YY', 'PFE007'),
    ('PFESECG6YY', 'PFE008'),
    ('PFESECG7YY', 'PFE009'),
    ('UNVGOFECG', 'UNVG101'),
    ('UNVGOFECG', 'UNVG103'),
    ('UNVGOFECG', 'UNVG105'),
    ('UNVGOFECG', 'UNVG107'),
    ('UNVGOFECG', 'UNVG109'),
    ('UNVGOFECG', 'UNVG111'),
    ('UNVSEC', 'UNVG101'),
    ('UNVSEC', 'UNVG103'),
    ('UNVSEC', 'UNVG105'),
    ('UNVSEC', 'UNVG107'),
    ('UNVSEC', 'UNVG109'),
    ('UNVSEC', 'UNVG111')
) AS v(group_code, course_code)
JOIN curriculum.elective_groups g ON g.code = v.group_code
JOIN curriculum.courses c ON c.code = v.course_code
ON CONFLICT DO NOTHING;

-- Ön koşullar
INSERT INTO curriculum.course_prerequisites (course_id, prerequisite_course_id, requirement, group_no)
SELECT c.id, p.id, v.requirement, v.group_no
FROM (VALUES
    ('COM2044', 'COM1002', 'PASSED', 1),
    ('COM2067', 'COM1002', 'ATTENDED', 1)
) AS v(course_code, prerequisite_code, requirement, group_no)
JOIN curriculum.courses c ON c.code = v.course_code
JOIN curriculum.courses p ON p.code = v.prerequisite_code
ON CONFLICT ON CONSTRAINT course_prerequisites_pair_key DO NOTHING;

-- Eşdeğerlikler: yeni kod ↔ eski kod
INSERT INTO curriculum.course_equivalences (course_id, equivalent_course_id, is_bidirectional, valid_from_year, note)
SELECT n.id, o.id, true, 2026, v.note
FROM (VALUES
    ('CEN3338', 'CEN338', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM1007', 'COM1001', '2026 ders planı intibak tablosu'),
    ('COM1015', 'COM1013', '2026 ders planı intibak tablosu'),
    ('COM2039', 'COM2031', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM2043', 'COM2041', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM2077', 'COM2075', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM3023', 'COM3025', '2026 ders planı intibak tablosu'),
    ('COM3023', 'COM3525', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM3033', 'COM3035', '2026 ders planı intibak tablosu'),
    ('COM3066', 'COM3064', '2026 ders planı intibak tablosu'),
    ('COM3070', 'COM3068', '2026 ders planı intibak tablosu'),
    ('COM3073', 'COM3071', '2026 ders planı intibak tablosu'),
    ('COM3074', 'COM3072', '2026 ders planı intibak tablosu'),
    ('COM3537', 'COM3037', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4063', 'COM4061', '2026 ders planı intibak tablosu'),
    ('COM4064', 'COM4062', '2026 ders planı intibak tablosu'),
    ('COM4080', 'COM4504', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4097', 'COM4099', '2026 ders planı intibak tablosu'),
    ('COM4551', 'COM4501', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4552', 'COM4502', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4553', 'COM4503', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4555', 'COM4505', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4556', 'COM4506', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4557', 'COM4507', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4558', 'COM4508', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4559', 'COM4509', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4560', 'COM4510', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4561', 'COM4511', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4562', 'COM4512', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4565', 'COM4515', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4566', 'COM4516', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4567', 'COM4517', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4568', 'COM4518', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('COM4569', 'COM4519', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('HIS103', 'HIS101', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('HIS104', 'HIS102', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('MTH0143', 'MTH0141', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('MTH0144', 'MTH0142', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('PHY0105', 'PHY0101', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('PHY0106', 'PHY0102', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('TUR171', 'TUR101', 'Aynı içerikli dersin yeni kodu (2026 ders planı)'),
    ('TUR174', 'TUR102', 'Aynı içerikli dersin yeni kodu (2026 ders planı)')
) AS v(new_code, old_code, note)
JOIN curriculum.courses n ON n.code = v.new_code
JOIN curriculum.courses o ON o.code = v.old_code
WHERE NOT EXISTS (
    SELECT 1 FROM curriculum.course_equivalences e
    WHERE (e.course_id = n.id AND e.equivalent_course_id = o.id) OR (e.course_id = o.id AND e.equivalent_course_id = n.id)
);

-- 2022 ders planı: 2018-2022 girişliler
WITH cur AS (
    INSERT INTO curriculum.curricula (program_id, name_tr, name_en, effective_from_year, effective_to_year,
                                      total_ects_required, status, activated_at)
    SELECT p.id, '2022 Ders Planı', '2022 Curriculum', 2018, 2022, 240, 'ACTIVE', now()
    FROM org.programs p
    WHERE p.code = 'BIL-EN-NO'
      AND NOT EXISTS (SELECT 1 FROM curriculum.curricula c WHERE c.program_id = p.id AND c.effective_from_year = 2018)
    RETURNING id
)
INSERT INTO curriculum.curriculum_items (curriculum_id, semester_no, item_type, course_id, elective_group_id,
                                         slot_theory_hours, slot_practice_hours, slot_national_credit, slot_ects,
                                         slot_course_count, is_compulsory, position)
SELECT cur.id, v.semester, v.item_type, c.id, g.id, v.theory, v.practice, v.credit, v.ects, v.course_count,
       v.item_type = 'COURSE', v.position
FROM cur
CROSS JOIN (VALUES
    (1, 'COURSE', 'COM1001', NULL, NULL, NULL, NULL, NULL, 0),
    (1, 'COURSE', 'COM1013', NULL, NULL, NULL, NULL, NULL, 1),
    (1, 'COURSE', 'PHY0101', NULL, NULL, NULL, NULL, NULL, 2),
    (1, 'COURSE', 'PHY0151', NULL, NULL, NULL, NULL, NULL, 3),
    (1, 'COURSE', 'MTH0141', NULL, NULL, NULL, NULL, NULL, 4),
    (1, 'COURSE', 'TUR101', NULL, NULL, NULL, NULL, NULL, 5),
    (1, 'COURSE', 'HIS101', NULL, NULL, NULL, NULL, NULL, 6),
    (1, 'COURSE', 'OUL101', NULL, NULL, NULL, NULL, NULL, 7),
    (1, 'COURSE', 'ENG101', NULL, NULL, NULL, NULL, NULL, 8),
    (1, 'ELECTIVE_SLOT', 'GENELSOSSEC', 0, 2, 0.0, 2.0, 1, 9),
    (2, 'COURSE', 'COM1002', NULL, NULL, NULL, NULL, NULL, 0),
    (2, 'COURSE', 'PHY0102', NULL, NULL, NULL, NULL, NULL, 1),
    (2, 'COURSE', 'PHY0152', NULL, NULL, NULL, NULL, NULL, 2),
    (2, 'COURSE', 'MTH0142', NULL, NULL, NULL, NULL, NULL, 3),
    (2, 'COURSE', 'MTH0120', NULL, NULL, NULL, NULL, NULL, 4),
    (2, 'COURSE', 'TUR102', NULL, NULL, NULL, NULL, NULL, 5),
    (2, 'COURSE', 'HIS102', NULL, NULL, NULL, NULL, NULL, 6),
    (2, 'COURSE', 'OUL102', NULL, NULL, NULL, NULL, NULL, 7),
    (2, 'COURSE', 'ENG102', NULL, NULL, NULL, NULL, NULL, 8),
    (3, 'COURSE', 'COM2031', NULL, NULL, NULL, NULL, NULL, 0),
    (3, 'COURSE', 'COM2041', NULL, NULL, NULL, NULL, NULL, 1),
    (3, 'COURSE', 'COM2067', NULL, NULL, NULL, NULL, NULL, 2),
    (3, 'COURSE', 'COM2075', NULL, NULL, NULL, NULL, NULL, 3),
    (3, 'COURSE', 'ENG201', NULL, NULL, NULL, NULL, NULL, 4),
    (3, 'ELECTIVE_SLOT', 'COMTE02', 3, 0, 3.0, 4.0, 1, 5),
    (4, 'COURSE', 'COM2044', NULL, NULL, NULL, NULL, NULL, 0),
    (4, 'COURSE', 'COM2058', NULL, NULL, NULL, NULL, NULL, 1),
    (4, 'COURSE', 'STA250', NULL, NULL, NULL, NULL, NULL, 2),
    (4, 'COURSE', 'MTH0210', NULL, NULL, NULL, NULL, NULL, 3),
    (4, 'COURSE', 'ENG202', NULL, NULL, NULL, NULL, NULL, 4),
    (4, 'ELECTIVE_SLOT', 'COMTE02', 3, 0, 3.0, 4.0, 1, 5),
    (4, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 6),
    (5, 'COURSE', 'COM3035', NULL, NULL, NULL, NULL, NULL, 0),
    (5, 'COURSE', 'COM3037', NULL, NULL, NULL, NULL, NULL, 1),
    (5, 'COURSE', 'COM3067', NULL, NULL, NULL, NULL, NULL, 2),
    (5, 'COURSE', 'COM3071', NULL, NULL, NULL, NULL, NULL, 3),
    (5, 'COURSE', 'SCS301', NULL, NULL, NULL, NULL, NULL, 4),
    (5, 'ELECTIVE_SLOT', 'COMTE03', 6, 0, 6.0, 8.0, 2, 5),
    (5, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 6),
    (6, 'COURSE', 'COM3032', NULL, NULL, NULL, NULL, NULL, 0),
    (6, 'COURSE', 'COM3064', NULL, NULL, NULL, NULL, NULL, 1),
    (6, 'COURSE', 'COM3068', NULL, NULL, NULL, NULL, NULL, 2),
    (6, 'COURSE', 'COM3076', NULL, NULL, NULL, NULL, NULL, 3),
    (6, 'COURSE', 'COM3072', NULL, NULL, NULL, NULL, NULL, 4),
    (6, 'COURSE', 'PPL302', NULL, NULL, NULL, NULL, NULL, 5),
    (6, 'ELECTIVE_SLOT', 'COMTE03', 3, 0, 3.0, 4.0, 1, 6),
    (6, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 7),
    (7, 'COURSE', 'COM4061', NULL, NULL, NULL, NULL, NULL, 0),
    (7, 'COURSE', 'COM4099', NULL, NULL, NULL, NULL, NULL, 1),
    (7, 'ELECTIVE_SLOT', 'COMTE04', 6, 0, 6.0, 12.0, 2, 2),
    (7, 'ELECTIVE_SLOT', 'UNVSEC', 4, 0, 4.0, 6.0, 2, 3),
    (8, 'COURSE', 'COM4062', NULL, NULL, NULL, NULL, NULL, 0),
    (8, 'ELECTIVE_SLOT', 'COMTE04', 9, 0, 9.0, 18.0, 3, 1),
    (8, 'ELECTIVE_SLOT', 'UNVSEC', 4, 0, 4.0, 6.0, 2, 2)
) AS v(semester, item_type, code, theory, practice, credit, ects, course_count, position)
LEFT JOIN curriculum.courses c ON v.item_type = 'COURSE' AND c.code = v.code
LEFT JOIN curriculum.elective_groups g ON v.item_type = 'ELECTIVE_SLOT' AND g.code = v.code;

-- 2023 ders planı: 2023-2025 girişliler
WITH cur AS (
    INSERT INTO curriculum.curricula (program_id, name_tr, name_en, effective_from_year, effective_to_year,
                                      total_ects_required, status, activated_at)
    SELECT p.id, '2023 Ders Planı', '2023 Curriculum', 2023, 2025, 240, 'ACTIVE', now()
    FROM org.programs p
    WHERE p.code = 'BIL-EN-NO'
      AND NOT EXISTS (SELECT 1 FROM curriculum.curricula c WHERE c.program_id = p.id AND c.effective_from_year = 2023)
    RETURNING id
)
INSERT INTO curriculum.curriculum_items (curriculum_id, semester_no, item_type, course_id, elective_group_id,
                                         slot_theory_hours, slot_practice_hours, slot_national_credit, slot_ects,
                                         slot_course_count, is_compulsory, position)
SELECT cur.id, v.semester, v.item_type, c.id, g.id, v.theory, v.practice, v.credit, v.ects, v.course_count,
       v.item_type = 'COURSE', v.position
FROM cur
CROSS JOIN (VALUES
    (1, 'COURSE', 'COM1001', NULL, NULL, NULL, NULL, NULL, 0),
    (1, 'COURSE', 'COM1013', NULL, NULL, NULL, NULL, NULL, 1),
    (1, 'COURSE', 'PHY0101', NULL, NULL, NULL, NULL, NULL, 2),
    (1, 'COURSE', 'PHY0151', NULL, NULL, NULL, NULL, NULL, 3),
    (1, 'COURSE', 'MTH0141', NULL, NULL, NULL, NULL, NULL, 4),
    (1, 'COURSE', 'TUR101', NULL, NULL, NULL, NULL, NULL, 5),
    (1, 'COURSE', 'HIS101', NULL, NULL, NULL, NULL, NULL, 6),
    (1, 'COURSE', 'OUL101', NULL, NULL, NULL, NULL, NULL, 7),
    (1, 'COURSE', 'ENG101', NULL, NULL, NULL, NULL, NULL, 8),
    (1, 'ELECTIVE_SLOT', 'GENELSOSSEC', 0, 2, 0.0, 2.0, 1, 9),
    (2, 'COURSE', 'COM1002', NULL, NULL, NULL, NULL, NULL, 0),
    (2, 'COURSE', 'PHY0102', NULL, NULL, NULL, NULL, NULL, 1),
    (2, 'COURSE', 'PHY0152', NULL, NULL, NULL, NULL, NULL, 2),
    (2, 'COURSE', 'MTH0142', NULL, NULL, NULL, NULL, NULL, 3),
    (2, 'COURSE', 'MTH0120', NULL, NULL, NULL, NULL, NULL, 4),
    (2, 'COURSE', 'TUR102', NULL, NULL, NULL, NULL, NULL, 5),
    (2, 'COURSE', 'HIS102', NULL, NULL, NULL, NULL, NULL, 6),
    (2, 'COURSE', 'OUL102', NULL, NULL, NULL, NULL, NULL, 7),
    (2, 'COURSE', 'ENG102', NULL, NULL, NULL, NULL, NULL, 8),
    (3, 'COURSE', 'COM2039', NULL, NULL, NULL, NULL, NULL, 0),
    (3, 'COURSE', 'COM2043', NULL, NULL, NULL, NULL, NULL, 1),
    (3, 'COURSE', 'COM2067', NULL, NULL, NULL, NULL, NULL, 2),
    (3, 'COURSE', 'COM2077', NULL, NULL, NULL, NULL, NULL, 3),
    (3, 'COURSE', 'ENG201', NULL, NULL, NULL, NULL, NULL, 4),
    (3, 'ELECTIVE_SLOT', 'COMTE02', 3, 0, 3.0, 4.0, 1, 5),
    (3, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 6),
    (4, 'COURSE', 'COM2044', NULL, NULL, NULL, NULL, NULL, 0),
    (4, 'COURSE', 'COM2058', NULL, NULL, NULL, NULL, NULL, 1),
    (4, 'COURSE', 'STA250', NULL, NULL, NULL, NULL, NULL, 2),
    (4, 'COURSE', 'MTH0210', NULL, NULL, NULL, NULL, NULL, 3),
    (4, 'COURSE', 'ENG202', NULL, NULL, NULL, NULL, NULL, 4),
    (4, 'ELECTIVE_SLOT', 'COMTE02', 3, 0, 3.0, 4.0, 1, 5),
    (4, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 6),
    (5, 'COURSE', 'COM3025', NULL, NULL, NULL, NULL, NULL, 0),
    (5, 'COURSE', 'COM3035', NULL, NULL, NULL, NULL, NULL, 1),
    (5, 'COURSE', 'COM3067', NULL, NULL, NULL, NULL, NULL, 2),
    (5, 'COURSE', 'COM3071', NULL, NULL, NULL, NULL, NULL, 3),
    (5, 'COURSE', 'SCS301', NULL, NULL, NULL, NULL, NULL, 4),
    (5, 'ELECTIVE_SLOT', 'COMTE03', 6, 0, 6.0, 8.0, 2, 5),
    (5, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 6),
    (6, 'COURSE', 'COM3032', NULL, NULL, NULL, NULL, NULL, 0),
    (6, 'COURSE', 'COM3064', NULL, NULL, NULL, NULL, NULL, 1),
    (6, 'COURSE', 'COM3068', NULL, NULL, NULL, NULL, NULL, 2),
    (6, 'COURSE', 'COM3076', NULL, NULL, NULL, NULL, NULL, 3),
    (6, 'COURSE', 'COM3072', NULL, NULL, NULL, NULL, NULL, 4),
    (6, 'COURSE', 'PPL302', NULL, NULL, NULL, NULL, NULL, 5),
    (6, 'ELECTIVE_SLOT', 'COMTE03', 3, 0, 3.0, 4.0, 1, 6),
    (6, 'ELECTIVE_SLOT', 'UNVSEC', 2, 0, 2.0, 3.0, 1, 7),
    (7, 'COURSE', 'COM4061', NULL, NULL, NULL, NULL, NULL, 0),
    (7, 'COURSE', 'COM4099', NULL, NULL, NULL, NULL, NULL, 1),
    (7, 'ELECTIVE_SLOT', 'COMTE04', 9, 0, 9.0, 18.0, 3, 2),
    (8, 'COURSE', 'COM4062', NULL, NULL, NULL, NULL, NULL, 0),
    (8, 'ELECTIVE_SLOT', 'COMTE04', 12, 0, 12.0, 24.0, 4, 1)
) AS v(semester, item_type, code, theory, practice, credit, ects, course_count, position)
LEFT JOIN curriculum.courses c ON v.item_type = 'COURSE' AND c.code = v.code
LEFT JOIN curriculum.elective_groups g ON v.item_type = 'ELECTIVE_SLOT' AND g.code = v.code;

-- 2026 ders planı: 2026 ve sonrası girişliler
WITH cur AS (
    INSERT INTO curriculum.curricula (program_id, name_tr, name_en, effective_from_year, effective_to_year,
                                      total_ects_required, status, activated_at)
    SELECT p.id, '2026 Ders Planı', '2026 Curriculum', 2026, NULL, 240, 'ACTIVE', now()
    FROM org.programs p
    WHERE p.code = 'BIL-EN-NO'
      AND NOT EXISTS (SELECT 1 FROM curriculum.curricula c WHERE c.program_id = p.id AND c.effective_from_year = 2026)
    RETURNING id
)
INSERT INTO curriculum.curriculum_items (curriculum_id, semester_no, item_type, course_id, elective_group_id,
                                         slot_theory_hours, slot_practice_hours, slot_national_credit, slot_ects,
                                         slot_course_count, is_compulsory, position)
SELECT cur.id, v.semester, v.item_type, c.id, g.id, v.theory, v.practice, v.credit, v.ects, v.course_count,
       v.item_type = 'COURSE', v.position
FROM cur
CROSS JOIN (VALUES
    (1, 'COURSE', 'COM1007', NULL, NULL, NULL, NULL, NULL, 0),
    (1, 'COURSE', 'COM1015', NULL, NULL, NULL, NULL, NULL, 1),
    (1, 'COURSE', 'PHY0105', NULL, NULL, NULL, NULL, NULL, 2),
    (1, 'COURSE', 'PHY0151', NULL, NULL, NULL, NULL, NULL, 3),
    (1, 'COURSE', 'MTH0143', NULL, NULL, NULL, NULL, NULL, 4),
    (1, 'COURSE', 'TUR171', NULL, NULL, NULL, NULL, NULL, 5),
    (1, 'COURSE', 'HIS103', NULL, NULL, NULL, NULL, NULL, 6),
    (1, 'COURSE', 'OUL101', NULL, NULL, NULL, NULL, NULL, 7),
    (1, 'COURSE', 'ENG101', NULL, NULL, NULL, NULL, NULL, 8),
    (2, 'COURSE', 'COM1002', NULL, NULL, NULL, NULL, NULL, 0),
    (2, 'COURSE', 'PHY0106', NULL, NULL, NULL, NULL, NULL, 1),
    (2, 'COURSE', 'PHY0152', NULL, NULL, NULL, NULL, NULL, 2),
    (2, 'COURSE', 'MTH0144', NULL, NULL, NULL, NULL, NULL, 3),
    (2, 'COURSE', 'MTH0120', NULL, NULL, NULL, NULL, NULL, 4),
    (2, 'COURSE', 'TUR174', NULL, NULL, NULL, NULL, NULL, 5),
    (2, 'COURSE', 'HIS104', NULL, NULL, NULL, NULL, NULL, 6),
    (2, 'COURSE', 'OUL102', NULL, NULL, NULL, NULL, NULL, 7),
    (2, 'COURSE', 'ENG102', NULL, NULL, NULL, NULL, NULL, 8),
    (3, 'COURSE', 'COM2039', NULL, NULL, NULL, NULL, NULL, 0),
    (3, 'COURSE', 'COM2043', NULL, NULL, NULL, NULL, NULL, 1),
    (3, 'COURSE', 'COM2067', NULL, NULL, NULL, NULL, NULL, 2),
    (3, 'COURSE', 'COM2077', NULL, NULL, NULL, NULL, NULL, 3),
    (3, 'COURSE', 'ENG201', NULL, NULL, NULL, NULL, NULL, 4),
    (3, 'ELECTIVE_SLOT', 'COMTE02', 3, 0, 3.0, 4.0, 1, 5),
    (3, 'ELECTIVE_SLOT', 'UNVGOFECG', 2, 0, 2.0, 3.0, 1, 6),
    (3, 'ELECTIVE_SLOT', 'PFESECG3YY', 0, 0, 0.0, 0.0, 2, 7),
    (4, 'COURSE', 'COM2044', NULL, NULL, NULL, NULL, NULL, 0),
    (4, 'COURSE', 'COM2058', NULL, NULL, NULL, NULL, NULL, 1),
    (4, 'COURSE', 'STA250', NULL, NULL, NULL, NULL, NULL, 2),
    (4, 'COURSE', 'MTH0210', NULL, NULL, NULL, NULL, NULL, 3),
    (4, 'COURSE', 'ENG202', NULL, NULL, NULL, NULL, NULL, 4),
    (4, 'ELECTIVE_SLOT', 'COMTE02', 3, 0, 3.0, 4.0, 1, 5),
    (4, 'ELECTIVE_SLOT', 'UNVGOFECG', 2, 0, 2.0, 3.0, 1, 6),
    (4, 'ELECTIVE_SLOT', 'PFESECG4YY', 0, 0, 0.0, 0.0, 2, 7),
    (5, 'COURSE', 'COM3023', NULL, NULL, NULL, NULL, NULL, 0),
    (5, 'COURSE', 'COM3033', NULL, NULL, NULL, NULL, NULL, 1),
    (5, 'COURSE', 'COM3067', NULL, NULL, NULL, NULL, NULL, 2),
    (5, 'COURSE', 'COM3073', NULL, NULL, NULL, NULL, NULL, 3),
    (5, 'COURSE', 'SCS301', NULL, NULL, NULL, NULL, NULL, 4),
    (5, 'ELECTIVE_SLOT', 'COMTE03', 6, 0, 6.0, 8.0, 2, 5),
    (5, 'ELECTIVE_SLOT', 'PFESECG5YY', 0, 0, 0.0, 0.0, 2, 6),
    (6, 'COURSE', 'COM3032', NULL, NULL, NULL, NULL, NULL, 0),
    (6, 'COURSE', 'COM3066', NULL, NULL, NULL, NULL, NULL, 1),
    (6, 'COURSE', 'COM3070', NULL, NULL, NULL, NULL, NULL, 2),
    (6, 'COURSE', 'COM3076', NULL, NULL, NULL, NULL, NULL, 3),
    (6, 'COURSE', 'COM3074', NULL, NULL, NULL, NULL, NULL, 4),
    (6, 'COURSE', 'PPL302', NULL, NULL, NULL, NULL, NULL, 5),
    (6, 'ELECTIVE_SLOT', 'COMTE03', 6, 0, 6.0, 8.0, 2, 6),
    (6, 'ELECTIVE_SLOT', 'PFESECG6YY', 0, 0, 0.0, 0.0, 2, 7),
    (7, 'COURSE', 'COM4063', NULL, NULL, NULL, NULL, NULL, 0),
    (7, 'COURSE', 'COM4097', NULL, NULL, NULL, NULL, NULL, 1),
    (7, 'ELECTIVE_SLOT', 'COMTE04', 12, 0, 12.0, 16.0, 4, 2),
    (7, 'ELECTIVE_SLOT', 'PFESECG7YY', 0, 0, 0.0, 0.0, 1, 3),
    (8, 'COURSE', 'COM4064', NULL, NULL, NULL, NULL, NULL, 0),
    (8, 'COURSE', 'COM4080', NULL, NULL, NULL, NULL, NULL, 1),
    (8, 'ELECTIVE_SLOT', 'COMTE04', 12, 0, 12.0, 16.0, 4, 2)
) AS v(semester, item_type, code, theory, practice, credit, ects, course_count, position)
LEFT JOIN curriculum.courses c ON v.item_type = 'COURSE' AND c.code = v.code
LEFT JOIN curriculum.elective_groups g ON v.item_type = 'ELECTIVE_SLOT' AND g.code = v.code;
